---

- name: Ensure Postgres is started
  ansible.builtin.service:
    name: "{{ devture_postgres_identifier }}"
    state: started
    daemon_reload: true
  register: devture_postgres_ensure_started_result

- name: Wait a bit, so that Postgres can start
  when: devture_postgres_ensure_started_result.changed | bool
  ansible.builtin.wait_for:
    timeout: "{{ devture_postgres_managed_databases_postgres_start_wait_timeout_seconds }}"
  delegate_to: 127.0.0.1
  become: false

# If Postgres is up from before, but it had originally been installed on a different container network,
# trying to prepare databases by connecting to `devture_postgres_container_network` would fail.
# For this reason, we determine and use the currently used network.
# Restarting the service later would put it in the corrent network.
- name: Check Postgres container network
  ansible.builtin.command: "{{ devture_systemd_docker_base_host_command_docker }} container inspect {{ devture_postgres_identifier }} --format '{% raw %}{{.HostConfig.NetworkMode}}{% endraw %}'"
  register: devture_postgres_container_network_check_result
  changed_when: false

- name: Set Postgres container network to use for preparing databases
  ansible.builtin.set_fact:
    devture_postgres_container_network_for_preparing_databases: "{{ devture_postgres_container_network_check_result.stdout }}"

- name: Prepare managed Postgres database
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/prepare_managed_database.yml"
  with_items: "{{ devture_postgres_managed_databases }}"
  loop_control:
    loop_var: managed_db
  # Suppress logging to avoid dumping the credentials to the shell
  no_log: true

- name: Ensure Postgres is stopped, if it originally was and if we are configured to do it
  when: devture_postgres_systemd_service_stop_originally_stopped_after_preparation | bool and devture_postgres_ensure_started_result.changed | bool
  ansible.builtin.service:
    name: "{{ devture_postgres_identifier }}"
    state: stopped
